// src/data.js

export const personalInfo = {
  name: "Kelvin",
  surname: "Kariuki",
  role: "Full-Stack Developer",
  tagline: "Building Secure, Scalable Systems",
  bio: "BSc. IT undergraduate at the University of Embu. I architect production-grade full-stack applications — from database schema to cloud deployment. Focused on Mobile Security, Hybrid E2EE, Networking and real-time systems.",
  email: "kelvinkariuki.dev@gmail.com",
  location: "Nyeri, Kenya",
  phone: "+254 769 791 611",
  github: "https://github.com/NIVLEKI",
  linkedin: "https://linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=kelvin-kariuki-9644a5333",
  whatsapp: "https://wa.me/254717328354?text=Hello%2C%20This%20is%20Kelvin%20Kariuki",
  instagram: "https://instagram.com/Niv.l3k",
  discord: "https://discord.com/users/1333756609125679144",
};

export const experience = [
  {
    role: "IT Intern",
    company: "Chinga Tea Factory Company Ltd",
    period: "May 2025 – Aug 2025",
    type: "Internship",
    icon: "fas fa-leaf",
    color: "#22c55e",
    points: [
      "Operated the ERP system (SAP) supporting core business and internal data management workflows",
      "Used POS scanners and field tools to process tea leaf deliveries from farmers",
      "Processed farmer loan applications and disbursements via the GreenFedha platform",
      "Issued insurance covers through the Majani Insurance system",
      "Manned the customer care desk — resolving farmer queries and account issues",
    ],
  },
];

export const skills = [
  {
    category: "Frontend",
    icon: "fas fa-layer-group",
    color: "#38bdf8",
    items: ["React / Next.js", "JavaScript", "Tailwind CSS", "Flutter / Dart"],
  },
  {
    category: "Backend",
    icon: "fas fa-server",
    color: "#818cf8",
    items: ["Node.js / Express", "Python / Django", "REST APIs", "Socket.io"],
  },
  {
    category: "Database & ORM",
    icon: "fas fa-database",
    color: "#2dd4bf",
    items: ["PostgreSQL", "MySQL / SQL", "Prisma ORM", "Supabase"],
  },
  {
    category: "Cloud & DevOps",
    icon: "fas fa-cloud",
    color: "#fb923c",
    items: ["AWS EC2 / S3", "Nginx", "PM2", "Netlify / Docker"],
  },
  {
    category: "Security",
    icon: "fas fa-shield-halved",
    color: "#f43f5e",
    items: ["AES-256 / RSA-2048", "End-to-End Encryption", "JWT / bcrypt", "Mobile Security"],
  },
  {
    category: "Mobile & Tools",
    icon: "fas fa-mobile-screen",
    color: "#a3e635",
    items: ["Android Studio", "Java", "Git / GitHub", "Data Visualization"],
  },
];

export const projects = [
  {
    title: "AQUAMY — Chama System",
    subtitle: "Full-Stack Financial Platform",
    desc: "Digitises the complete financial and administrative operations of a Kenyan community savings group (Chama). Constitution-driven design encodes fee amounts, loan policies, and role permissions directly into the app logic.",
    icon: "fas fa-coins",
    color: "#2dd4bf",
    tech: ["Next.js 14", "TypeScript", "NextAuth.js", "Prisma", "PostgreSQL", "M-Pesa API", "Docker"],
    highlights: ["17-model PostgreSQL schema", "9-role RBAC system", "M-Pesa Daraja STK Push integration", "Immutable AuditLog system"],
    image: "/images/aquamy.png",
    github: "https://github.com/NIVLEKI",
    demo: "https://aquamy-portal.vercel.app/",
    featured: true,
  },
  {
    title: "C2C Marketplace Platform",
    subtitle: "Full-Stack Real-Time Web App",
    desc: "A production-ready Consumer-to-Consumer marketplace with fully decoupled architecture. Users list items, browse a live feed, and negotiate via real-time private chat — without third-party apps.",
    icon: "fas fa-store",
    color: "#38bdf8",
    tech: ["Next.js 15", "Node.js", "Socket.io", "PostgreSQL", "Prisma", "AWS EC2", "AWS S3", "Nginx", "PM2", "JWT"],
    highlights: ["Real-time bidirectional WebSocket chat", "Live camera capture → AWS S3 upload", "PM2 zero-downtime deployment", "12+ REST endpoints"],
    image: "/images/c2c-marketplace.png",
    github: "https://github.com/NIVLEKI",
    demo: "",
    featured: true,
  },
  {
    title: "NivlockX",
    subtitle: "Hybrid E2EE Mobile File Storage",
    desc: "An Android application implementing Hybrid End-to-End Encryption for secure file storage and peer-to-peer sharing. Combines AES-256 symmetric encryption with RSA-2048 key exchange — same architecture as Signal.",
    icon: "fas fa-lock",
    color: "#818cf8",
    tech: ["Flutter", "Dart", "AES-256", "RSA-2048", "Android Studio"],
    highlights: ["Zero server-side plaintext exposure", "On-device encryption before transmission", "RSA-2048 key exchange", "APK available for download"],
    image: "/images/nivlockx.png",
    demo: "",
    apk: "/NivlockX.apk",
    featured: true,
  },
  {
    title: "WaterSafe Platform",
    subtitle: "Community Water Quality Monitor",
    desc: "A community-driven water quality monitoring system. Crowdsources real-time data on pH, turbidity, and chlorine levels with interactive Chart.js visualizations.",
    icon: "fas fa-droplet",
    color: "#06b6d4",
    tech: ["Django", "Python", "Chart.js", "Bootstrap 5"],
    highlights: ["Real-time pH & turbidity tracking", "Interactive Chart.js dashboards", "Community data crowdsourcing"],
    image: "/images/watersafe.png",
    github: "https://github.com/NIVLEKI",
    demo: "",
  },
  {
    title: "TenantFlex Housing",
    subtitle: "Housing Management App",
    desc: "A comprehensive housing management application for landlords and tenants featuring automated payment tracking and M-Pesa integration.",
    icon: "fas fa-building",
    color: "#fb923c",
    image: "/images/tenantflex.png",
    tech: ["Java", "Firebase", "MySQL", "M-Pesa API"],
    highlights: ["Automated payment tracking", "M-Pesa integration", "Landlord/tenant portals"],
    demo: "",
  },
  {
    title: "Nivlek Solutions",
    subtitle: "IT Consultancy & Web Services",
    desc: "My official IT Consultancy brand. Professional Web Development, SEO, and Technical Support services. Consistently rated 5-Stars on Google Reviews.",
    icon: "fas fa-briefcase",
    color: "#FFD700",
    tech: ["Founder", "Web Design", "SEO", "IT Support"],
    highlights: ["5-Star Google Reviews", "Local business clients", "Web Development & SEO"],
    image: "/images/nivlek-solutions.png",
    googleProfile: "https://share.google/tbdpFKl0bfrjFIGPE",
    demo: "https://nivleksolutions.co.ke",
    isVenture: true,
  },
];